apiVersion: v1
kind: Service
metadata:
  labels:
    app: cassandra
  name: cassandra-headless-svc
  namespace: dev
spec:
  selector:
    app: cassandra
  ports:
  - port: 9042
    # targetPort: <Target Port>
  clusterIP: None  #This makes this service an headless service. Only accessible by other pods (e.g: access from a webserver to a db server)
